
stages:
  - build
  - deploy

build:linux:x86_64:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os linux --arch x86_64 --target itch-setup
    - node release/build.js --os linux --arch x86_64 --target kitch-setup
  tags:
    - linux
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

build:windows:i686:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os windows --arch i686 --target itch-setup
    - node release/build.js --os windows --arch i686 --target kitch-setup
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

build:windows:x86_64:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os windows --arch x86_64 --target itch-setup
    - node release/build.js --os windows --arch x86_64 --target kitch-setup
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

build:darwin:x86_64:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os darwin --arch x86_64 --target itch-setup
    - node release/build.js --os darwin --arch x86_64 --target kitch-setup
  tags: 
    - darwin
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

deploy:
  stage: deploy
  tags:
    - linux
  script:
    - npm ci --no-audit
    - node release/deploy.js
