name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.13]

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libpango1.0-dev libpangocairo-1.0-0 libgdk-pixbuf2.0-dev libgtk-3-dev

    - name: Setup
      run: npm install

    - name: Build
      run: node release/build.js --target itch-setup --skip-signing

    - name: Store
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: artifacts/itch-setup/
